language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test
after_success:
  - npm run coverage
branches:
  only:
  - master
  - /^greenkeeper/.*$/
notifications:
  email: false
