language: node_js
node_js:
  - "8"
install:
  - npm install -g codecov
after_script:
  - npm run codecov
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - /^greenkeeper/.*$/
notifications:
  email: false
